[package]
name = "tcgdb"
version = "0.1.0"
authors = ["Michael Bryan <michaelbryan122@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled"] }